let clientes = [
  {
    id: 1,
    isEditing: false,
    mascota: "Atapuerco",
    especie: "cerdo",
    raza: "vietnamita",
    imagen: "/media/client-pets/atapuerco.webp",
    isShowing: false,
    cliente: "Juan Simón",
    email: "juan.simon@pet-it.com",
    proximaCita: "2025-03-06",
    comentario:
      "Atapuerco no era capaz de encontrar trufas, pero le han arreglado los problemas de olfato y ahora es como un detector. ¡Servicio de 10!",
    calificacion: 0,
  },
  {
    id: 2,
    isEditing: false,
    mascota: "Piticli",
    especie: "loro",
    raza: "",
    imagen: "/media/client-pets/piticli.webp",
    isShowing: false,
    cliente: "Luis Fury",
    email: "fury.lopez@pet-it.com",
    proximaCita: "2025-03-06",
    comentario:
      "Gracias a la 'paticura' que le hicieron a Piticli ya no me desgarra cuando lo pongo en mi brazo.",
    calificacion: 0,
  },
  {
    id: 3,
    isEditing: false,
    mascota: "Freya",
    especie: "perro",
    raza: "",
    imagen: "/media/client-pets/freya.webp",
    isShowing: false,
    cliente: "Luis Simón",
    email: "luis.simon@pet-it.com",
    proximaCita: "2025-03-06",
    comentario:
      "Ha pasado de ser una perra hiperactiva a activa nada más, mis figuritas de Warhammer lo agradecen.",
    calificacion: 0,
  },
  {
    id: 4,
    isEditing: false,
    mascota: "Brunelleschi",
    especie: "gato",
    raza: "",
    imagen: "/media/client-pets/brunelleschi.webp",
    isShowing: false,
    cliente: "Eugenio Drosdov",
    email: "far.drosdov@pet-it.com",
    proximaCita: "2025-03-06",
    comentario:
      "Dejé a Brunne en el hotel de gatos y cuando fuia buscarlo el muy desgraciado no se quería ir. Habla muy bien del trato del hotel, ¡gracias!",
    calificacion: 0,
  },
];
