let clientes = [
    {
      id: 1,
      isEditing: false,
      mascota: "Atapuerco",
      especie: "cerdo",
      raza: "vietnamita",
      imagen: "/media/client-pets/atapuerco.webp",
      isShowing: false,
      cliente: "Juan Simón",
      email: "juan.simon@pet-it.com",
      proximaCita: "2025-03-06",
    },
    {
      id: 2,
      isEditing: false,
      mascota: "Piticli",
      especie: "loro",
      raza: "",
      imagen: "/media/client-pets/piticli.webp",
      isShowing: false,
      cliente: "Luis Fury",
      email: "fury.lopez@pet-it.com",
      proximaCita: "2025-03-06",
    },
    {
      id: 3,
      isEditing: false,
      mascota: "Freya",
      especie: "perro",
      raza: "",
      imagen: "/media/client-pets/freya.webp",
      isShowing: false,
      cliente: "Luis Simón",
      email: "luis.simon@pet-it.com",
      proximaCita: "2025-03-06",
    },
    {
      id: 4,
      isEditing: false,
      mascota: "Brunelleschi",
      especie: "gato",
      raza: "",
      imagen: "/media/client-pets/brunelleschi.webp",
      isShowing: false,
      cliente: "Eugenio Drosdov",
      email: "far.drosdov@pet-it.com",
      proximaCita: "2025-03-06",
    },
  ];